const PROJECT_SELECT = "PROJECT_SELECT";
const ABOUT_ME_SELECT = "ABOUTME_SELECT";
const CONTACT_SELECT = "CONTACT_SELECT";
const TTT_SELECT = "TTT_SELECT"
const SHOW_SNAKE = "SHOW_SNAKE";
const SHOW_CALC = "SHOW_CALC";
const SHOW_PATH_FIND = "SHOW_PATH_FIND"

export {PROJECT_SELECT};
export {ABOUT_ME_SELECT};
export {TTT_SELECT};
export {SHOW_SNAKE};
export {SHOW_CALC};
export {CONTACT_SELECT};
export {SHOW_PATH_FIND};
