const GAMES_SELECT = " GAMES_SELECT";
const ALGORITHMS_SELECT = "ALGORITHMS_SELECT";
const OTHERS_SELECT = "OTHERS_SELECT";
const START_SELECT = "START_SELECT";
const TTT_SELECT = "TTT_SELECT"
const SNAKE_SELECT = "SNAKE_SELECT"

export {GAMES_SELECT};
export {ALGORITHMS_SELECT};
export {OTHERS_SELECT};
export {START_SELECT};
export {TTT_SELECT};
export {SNAKE_SELECT};